name: Build Sovereign Titan APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libunwind-dev
          sudo apt-get install -y -f \
            build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
            libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good libsqlite3-dev \
            libffi-dev libssl-dev

      - name: Install Buildozer and Cython
        run: |
          pip install --user --upgrade buildozer Cython==0.29.33 setuptools

      - name: Build with Buildozer (Single Architecture)
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # قبول التراخيص
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          # تعديل ملف buildozer.spec برمجياً ليقوم ببناء نسخة واحدة فقط لتوفير الذاكرة
          sed -i 's/android.archs = arm64-v8a, armeabi-v7a/android.archs = arm64-v8a/' buildozer.spec
          # البدء في البناء
          yes | buildozer -v android debug
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SovereignTitan-Package
          path: bin/*.apk
